### ISSUE TITLE
Encountering Issue on Version 2024.4

### ISSUE THREAD

**Issue by NiceCozyHat** [t0stiman/rr_better_ui_mod#3]
![Screenshot 2024-07-01 200010](https://github.com/t0stiman/rr_better_ui_mod/assets/174392239/1b88a412-75c0-48c2-bcc9-15f26028692e)
I have no idea what it means, but I think it might be in relevance to the post above. Good Luck.

**Comment by NiceCozyHat** [comment]
Sorry, meant earlier post that was on May 22nd by Hr-Ravn).

**Comment by t0stiman** [comment]
Fixed
